"""add fields for users

Revision ID: a27ae623bc75
Revises: 0f51401c3063
Create Date: 2018-07-09 15:54:41.129492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27ae623bc75'
down_revision = '0f51401c3063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
